# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run build 
        npm test
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lib-docs
        path: |
          lib
          docs
          
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage/lcov-report/index.html
        
    - name: Upload lib Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: lib
        path: ./lib 
